### Services
GET http://{{client.url}}/api/services
    HTTP/1.1
Authorization: {{client.token}}

### Settings
GET http://{{client.url}}/api/setting?locale=fa&populate=*
    HTTP/1.1
Authorization: {{client.token}}

### Footer
GET http://{{client.url}}/api/footer?locale=fa&populate=*
    HTTP/1.1
Authorization: {{client.token}}

### Hero
GET http://{{client.url}}/api/hero-config?locale=fa&populate=*
    HTTP/1.1
Authorization: {{client.token}}

### Narratives
GET http://{{client.url}}/api/customer-narratives?locale=fa&populate=*
    HTTP/1.1
Authorization: {{client.token}}


### Narrative
GET http://{{client.url}}/api/customer-narratives?populate[hero][populate]=*&populate[problemstory][populate]=*
    HTTP/1.1
Authorization: {{client.token}}

